sudo: required
cache: pip
language: python
python:
- '2.7'
env:
  global:
  - secure: HijFiaxLo1b7gzqbLWxIRkkP8iomGA/iYHLIkraj1sH4pTIjZ6gLFYrl7s5bfXEgv2O3x1Q7jMsr8OvK6CABjx+SNZTANBEaTof8vzv+ydaB+HfAPpA0ojWYYgcZF+ScMvAhkCWE/I+tKHhzH5Z+VpBjJmiR5ltMa+UeuWlJ6YjqmIgrcKzqyl2s3CLYnrWxExtTQsUITf6MZg2nkaqQumXKOeO7iefVlM0D2fQbFo/RjeIPV5NU8oFaPavekbi4Vcj7wfd0M1zRII1l6xK3ux1aajZLZLC2tgQ43p4X8GtTCy1ymNeAfEc3gsrNkhz4rHXp/+asFWooBQeYMfsP8ZlUGmGAbvL19rtFHKVswHMq7tSnEKZsHEXZA4Q7qZl918/mkfXVEQ8v89wvBzk5wGrCkTDoLSQW7siZ5HRLCHiOsHlpVg7uy9X0BQ8XuIX6g6dafcsNOurAIvHLQiwg1nB3/N6mrYtICLojT2G8fV+9XCCU13iyJKQ7RGQuyzV/mW5U4/XVQzs6iN4ClwmE/0Oh50Bj1UVooqcKxZcSL8ydJM0WliH0f3qK1/5HILrQl3xX/0RqCqdZK/FnHjs0HLwONhKEd1+6zWnmGndxh/3oc8fX1SvwqNf52SuaPXFVWb48/a++fExv55WEpJxSKMFgiC0Bck36PZfIb8/oYsc=
  - secure: FdS+PfF/VxqT0g2AxYMBui/HJIRYkRCENdHaJ3tSmp6CPPSoyISbyk+TVBrpTtwdRwrp0u2VfieQhOAjgPoc1RoxuzdFMO0od/ezDMCiGNoj+/0y4arXPuwHnQT17IhxD+bY6vSgLdvLqfWYVLFws7pMiactjgsD/MDBDvJcO1Cnzf5skRJlQ/q71t6I8K5nSgDyUCmz9LCeqVo2hluGfBlSPG9JKG34oCLWcs98hnlsCtEIvJyrOZOrkX0SB7kFtvv2bo7A80i4zm5c+kE2+F6F8efbF5wI/77HxTeEokjgbt6Cc3kPgFKR/xRYaQWPcZFT/5TTWT+GBJAaIOWnKK2Ts5otcpKelg9t/875wKoNsarmBSQZ1rs+uwajxsYgoCasn3VEgqacNy47wuTegXNekr1lZeu5TbGBqCVy9zp1kvQRtLbu1NWZmFTQsuGHQez5hrEA2JRKeNn9jU8YkvWBwK6LWE+jMmPKq5Hz9wgaf4Th5Pqhr4mKEBm8hNmidqvW7CdMsVFDMwiKBqr6X9m/lqfaOT8CWnE5KTMwdyyBSqNdcAaW89iPyUNZpLwKKJ7RPasBUmGEEkaQMM6EQrD6wiF1vHgo88JmEo01um3OT2XbCnY1ODphKCh6V/WtXTQObx5S8dWoefMkUS/kJEhFbfI0JbJjvu8AlKNpASk=
services:
- docker
script: true
install:
- pip install -r requirements-robotframework.txt
deploy:
- provider: script
  script: bash ./scripts/docker_push.sh
  on:
    branch: develop
- provider: script
  script: bash ./scripts/docker_push.sh
  on:
    branch: cobusc-test-mods
