version: '3'

services:
    core-general:
        image: girleffect:1.0
        build:
            context: .

    core-authentication-service:
        image: ge-auth:0.1
        build:
            context: ../core-authentication-service/
        volumes:
            - ../core-authentication-service:/code
        command: scripts/waitFor.sh scripts/startDjango.sh
        ports:
            - "8000:8000"
        environment:
            - DB_HOST=db
            # NOTE: we bootstrap our database container with some dbs.
            - DB_NAME=authservice
        depends_on:
            - db

    wagtail-demo-1:
        image: wtd_1:0.1
        build:
            context: apps/wagtail_client/
        command: scripts/waitFor.sh scripts/startDjango.sh
        ports:
            - "8001:8001"
        environment:
            - DB_HOST=db
            - DB_NAME=wagtail_1
            - WAGTAIL_SITE_NAME=wagtail_1_demo
            - OIDC_RP_CLIENT_ID=asdasdasd
            - OIDC_RP_CLIENT_SECRET=asdasd
            - OIDC_OP_AUTHORIZATION_ENDPOINT=asdasd
            - OIDC_OP_TOKEN_ENDPOINT=asdasd
            - OIDC_OP_USER_ENDPOINT=asdasd
        depends_on:
            - db
            - core-authentication-service

    db:
        build:
            context: apps/database/
        environment:
            - WAGTAILDBS=wagtail_1 wagtail_2
        # To rather mount localhost postgres data.
        #volumes:
        #    - "/var/lib/postgresql/data:/var/lib/postgresql/data"
