version: '3'

# Refer to the .env file for IP and port-related definitions

services:

  core-user-data-store:
    build:
      context: ../core-user-data-store/
    environment:
      - DB_URI=postgresql+psycopg2://user_data_store:password@db:5432/user_data_store
    volumes:
      - ../core-user-data-store/:/app/
    ulimits:
       nproc: 65535
       nofile:
         soft: 20000
         hard: 40000
    restart: on-failure
    # command: /code/prism run --validate --debug --list --mockDynamic -s /code/swagger/user_data_store.yml -p 5000
    command: -m swagger_server
    depends_on:
      - db
    networks:
      oidcnetwork:
        ipv4_address: ${USER_DATA_STORE_IP}

  core-access-control:
    build:
      context: ../core-access-control/
    environment:
      - DB_URI=postgresql+psycopg2://access_control:password@db:5432/access_control
    volumes:
      - ../core-access-control/:/app/
    restart: on-failure
    # command: /code/prism run --validate --debug --list --mockDynamic -s /code/swagger/access_control.yml -p 5000
    command: -m swagger_server
    depends_on:
      - db
    networks:
      oidcnetwork:
        ipv4_address: ${ACCESS_CONTROL_IP}

  core-authentication-service:
    image: ge-auth:0.1
    build:
      context: ../core-authentication-service/
    volumes:
      - ../core-authentication-service/:/app/
    command: scripts/waitFor.sh scripts/startDjango.sh
    ports:
      - "${AUTHENTICATION_SERVICE_PORT}:8000"
    environment:
      - DB_HOST=db
      - REDIS_URI=redis://redis:6379/0
      # NOTE: we bootstrap our database container with some dbs.
      - DB_NAME=authentication_service
      - ALLOWED_HOSTS=*
      - WAGTAIL_1_IP=http://${WAGTAIL_DEMO_1_IP}:8000/oidc/callback/
      - WAGTAIL_2_IP=http://${WAGTAIL_DEMO_2_IP}:8000/oidc/callback/
    depends_on:
      - db
    networks:
      oidcnetwork:
        ipv4_address: ${AUTHENTICATION_SERVICE_IP}

  wagtail-demo-1:
    image: wtd_1:0.1
    build:
      context: ../core-integration-demo/
    command: scripts/waitFor.sh scripts/startDjango.sh
    ports:
      - "${WAGTAIL_DEMO_1_PORT}:8000"
    environment:
      # Not current on postgres.
      - DB_HOST=db
      - DB_NAME=wagtail_1
      - DB_USER=wagtail_1
      - DB_PASSWORD=password
      - WAGTAIL_SITE_NAME="Blue Wagtail"
      - WAGTAIL_SITE_COLOUR=blue
      - WAGTAIL_REDIRECT_URL=http://${WAGTAIL_DEMO_1_IP}:8000/
      - OIDC_RP_CLIENT_ID=client_id_1
      - OIDC_RP_CLIENT_SECRET=super_client_secret_1
      - OIDC_OP=http://${AUTHENTICATION_SERVICE_IP}:8000
      - OIDC_OP_AUTHORIZATION_ENDPOINT=http://${AUTHENTICATION_SERVICE_IP}:8000/openid/authorize/
      - OIDC_OP_TOKEN_ENDPOINT=http://${AUTHENTICATION_SERVICE_IP}:8000/openid/token/
      - OIDC_OP_USER_ENDPOINT=http://${AUTHENTICATION_SERVICE_IP}:8000/openid/userinfo/
    depends_on:
      - db
      - core-authentication-service
    volumes:
        - "../core-integration-demo/:/app/"
    networks:
      oidcnetwork:
        ipv4_address: ${WAGTAIL_DEMO_1_IP}

  wagtail-demo-2:
    image: wtd_2:0.1
    build:
      context: ../core-integration-demo/
    command: scripts/waitFor.sh scripts/startDjango.sh
    ports:
      - "${WAGTAIL_DEMO_2_PORT}:8000"
    environment:
      # Not current on postgres.
      - DB_HOST=db
      - DB_NAME=wagtail_2
      - DB_USER=wagtail_2
      - DB_PASSWORD=password
      - WAGTAIL_SITE_NAME="Green Wagtail"
      - WAGTAIL_SITE_COLOUR=green
      - WAGTAIL_REDIRECT_URL=http://${WAGTAIL_DEMO_2_IP}:8000/
      - OIDC_RP_CLIENT_ID=client_id_2
      - OIDC_RP_CLIENT_SECRET=super_client_secret_2
      - OIDC_OP=http://${AUTHENTICATION_SERVICE_IP}:8000
      - OIDC_OP_AUTHORIZATION_ENDPOINT=http://${AUTHENTICATION_SERVICE_IP}:8000/openid/authorize/
      - OIDC_OP_TOKEN_ENDPOINT=http://${AUTHENTICATION_SERVICE_IP}:8000/openid/token/
      - OIDC_OP_USER_ENDPOINT=http://${AUTHENTICATION_SERVICE_IP}:8000/openid/userinfo/
    depends_on:
      - db
      - core-authentication-service
    volumes:
        - "../core-integration-demo/:/app/"
    networks:
      oidcnetwork:
        ipv4_address: ${WAGTAIL_DEMO_2_IP}

  core-management-layer:
    build:
      context: ../core-management-layer/
    environment:
      - STUBS_CLASS=management_layer.integration.Implementation
      - PYTHONASYNCIODEBUG=0
      - ACCESS_CONTROL_API=http://${ACCESS_CONTROL_IP}:8080/api/v1
      - AUTHENTICATION_SERVICE_API=http://${AUTHENTICATION_SERVICE_IP}:8000/api/v1
      - USER_DATA_STORE_API=http://${USER_DATA_STORE_IP}:8080/api/v1
      - INSECURE=true
      - WITH_UI=true
      - UI_HOST=${MANAGEMENT_LAYER_IP}
      - JWT_SECRET=management_layer_workaround
      - JWT_AUDIENCE=management_layer_workaround
    volumes:
      - ../core-management-layer/:/app/
    ports:
      - "${MANAGEMENT_LAYER_PORT}:8000"
    ulimits:
       nproc: 65535
       nofile:
         soft: 20000
         hard: 40000
    depends_on:
      - core-access-control
      - core-user-data-store
      - core-authentication-service
    restart: on-failure
    # For mocking:
    # command: /code/prism run --validate --debug --list --mockDynamic -s /code/swagger/management_layer.yml -p 8080
    command: httpd.py --logging=debug
    networks:
      oidcnetwork:
        ipv4_address: ${MANAGEMENT_LAYER_IP}

  core-management-portal:
    image: ge-gmp:0.1
    build:
      context: ../core-management-portal/
    command: yarn start
    ports:
      - "${MANAGEMENT_PORTAL_PORT}:3000"
    environment:
      - OIDC_RP_CLIENT_ID=client_id_2
      - OIDC_RP_CLIENT_SECRET=super_client_secret_2
      - OIDC_OP_AUTHORIZATION_ENDPOINT=http://${AUTHENTICATION_SERVICE_IP}:8000/openid/authorize/
      - OIDC_OP_TOKEN_ENDPOINT=http://${AUTHENTICATION_SERVICE_IP}:8000/openid/token/
      - OIDC_OP_USER_ENDPOINT=http://${AUTHENTICATION_SERVICE_IP}:8000/openid/userinfo/
    depends_on:
      - core-authentication-service
    volumes:
        - "../core-management-portal/:/app/"
    networks:
      oidcnetwork:
        ipv4_address: ${MANAGEMENT_PORTAL_IP}

  db:
    build:
      context: apps/database/
    # To rather mount localhost postgres data.
    #volumes:
    #    - "/var/lib/postgresql/data:/var/lib/postgresql/data"
    networks:
      oidcnetwork:
        ipv4_address: ${POSTGRESQL_IP}

  redis:
    image: "redis:alpine"
    expose:
      - "6379"
    networks:
      oidcnetwork:
        ipv4_address: ${REDIS_IP}

  memcache:
    image: "memcached:alpine"
    expose:
      - "11211"
    networks:
      oidcnetwork:
        ipv4_address: ${MEMCACHE_IP}

  squid:
    image: "datadog/squid"
    expose:
      - "3128"
    ports:
      - "${SQUID_PORT}:3128"
    networks:
      oidcnetwork:
        ipv4_address: ${SQUID_IP}

networks:
  oidcnetwork:
    external: true

