version: "3"

services:
  localstack:
    image: "localstack/localstack:latest"
    build:
      context: ../apps/localstack/
    entrypoint: ./scripts/startUp.sh
    expose:
      - "4567" # API Gateway
      - "4568" # Kinesis
      - "4569" # DynamoDB
      - "4570" # DynamoDB Streams
      - "4571" # Elasticsearch
      - "4572" # S3
      - "4573" # Firehose
      - "4574" # Lambda
      - "4575" # SNS
      - "4576" # SQS
      - "4577" # Redshift
      - "4578" # Elasticsearch Service
      - "4579" # SES
      - "4580" # Route53
      - "4581" # CloudFormation
      - "4582" # CloudWatch
      - "4583" # SSM
      - "4584" # SecretsManager
      - "8080" # Web UI
    environment:
      - DEFAULT_REGION=us-east-1
      - FORCE_NONINTERACTIVE=True
      - AWS_ACCESS_KEY_ID=foobar
      - AWS_SECRET_ACCESS_KEY=foobar
      - TEST_STREAM=test-stream
    networks:
      - oidcnetwork
